name       : verilator
version    : '4.018'
release    : 7
source     :
    - https://www.veripool.org/ftp/verilator-4.018.tgz : 98d52ec125d21b452a8b0bfddf336d8f792a53449db26798978f47885a430346
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
