name       : verilator
version    : '4.010'
release    : 2
source     :
    - https://www.veripool.org/ftp/verilator-4.010.tgz : 5651748fe28e373ebf7a6364f5e7935ec9b39d29671f683f366e99d5e157d571
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
