name       : verilator
version    : '4.214'
release    : 25
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v4.214.tar.gz : e14c7f6ffb00a6746ae2a8ea0424e90a1a30067e8ae4c96b8c42689ca1ca0b1f
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
