name       : verilator
version    : '4.224'
release    : 30
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v4.224.tar.gz : 010ff2b5c76d4dbc2ed4a3278a5599ba35c8ed4c05690e57296d6b281591367b
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
