name       : verilator
version    : '4.228'
release    : 32
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v4.228.tar.gz : be6af6572757013802be5b0ff9c64cbf509e98066737866abaae692fe04edf09
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
