name       : verilator
version    : '4.216'
release    : 26
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v4.216.tar.gz : 64e5093b629a7e96178e3b2494f208955f218dfac6f310a91e4fc07d050c980b
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
