name       : verilator
version    : '5.002'
release    : 33
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v5.002.tar.gz : 72d68469fc1262e6288d099062b960a2f65e9425bdb546cba141a2507decd951
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
