name       : verilator
version    : '5.014'
release    : 37
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v5.014.tar.gz : 36e16c8a7c4b376f88d87411cea6ee68710e6d1382a13faf21f35d65b54df4a7
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
builddeps  :
    - help2man
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
