name       : verilator
version    : '4.212'
release    : 24
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v4.212.tar.gz : 7b655859e4e75c9673141aede8f5a20f47e4c380055d1a588d5be60cbbc73619
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
