name       : verilator
version    : 4.0.16
release    : 5
source     :
    - https://www.veripool.org/ftp/verilator-4.016.tgz : 328a8f85c4fb0ecdabbf56e3c261485234dd1c28211e413101c533fdaea9d8a1
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
