name       : verilator
version    : '5.012'
release    : 36
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v5.012.tar.gz : db19a7d7615b37d9108654e757427e4c3f44e6e973ed40dd5e0e80cc6beb8467
license    :
    - LGPL-3.0-only
    - Artistic-2.0
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
builddeps  :
    - help2man
rundeps    :
    - ccache
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    make test
