name       : verilator
version    : '4.014'
release    : 4
source     :
    - https://www.veripool.org/ftp/verilator-4.014.tgz : edf517b1b3ae0df98bd8d8189d17142c181cd50948d54a6ecb082f38804a33eb
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
