name       : verilator
version    : '4.012'
release    : 3
source     :
    - https://www.veripool.org/ftp/verilator-4.012.tgz : 515d72b3a9e1b291b05b58f3635df7f8f4fa53103bbe1cddefb8bc70bf6af677
license    :
    - LGPL-3.0-only
    - Artistic-2.0
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
